version: '3'
services:
  toposoid-contents-admin-web:
    image: toposoid-contents-admin-web:0.6-SNAPSHOT
    tty: true
    environment:
      - TOPOSOID_CONTENTS_URL=http://toposoid-contents-admin-web:9012/
    ports:
      - 9012:9012
  